FROM node:16-alpine as builder
ENV HOME=/home/node/app
WORKDIR $HOME

ARG BUILD_COMMAND=build
COPY . .

RUN npm install && RUN npm run ${BUILD_COMMAND}

FROM node:16-alpine

WORKDIR /home/node/app

COPY --from=builder /home/node/app .

EXPOSE 8080
CMD ["npm", "run", "start"]