FROM node:16-alpine as builder

WORKDIR /home/node/app

COPY . .

RUN npm install && npm run build

FROM nginx:stable-alpine

COPY --from=builder /home/node/app/build /usr/share/nginx/html
COPY --from=builder /home/node/app/nginx.conf /etc/nginx/conf.d/default.conf