export const sections = {
  FEATURES_WITH_IMAGE: "FEATURES_WITH_IMAGE",
  FAQ_ONE: "FAQ_ONE",
  FOOTER_CTA: "FOOTER_CTA",
  HERO_FIVE: "HERO_FIVE",
  SIMPLE_HEADER: "SIMPLE_HEADER",
  TEXT_WITH_IMAGE: "TEXT_WITH_IMAGE",
  SIMPLE_TEXT: "SIMPLE_TEXT",
  TESTIMONIALS_ONE: "TESTIMONIALS_ONE",
  WORK_PROCESS_TWO: "WORK_PROCESS_TWO",
  WORK_PROCESS_FOUR: "WORK_PROCESS_FOUR",
};

export const CTAs = {
  COMPARE_RATES: "COMPARE_RATES",
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  SUBSCRIBE: "SUBSCRIBE",
  LEARNING_CENTER: "LEARNING_CENTER",
};
